### ISSUE TITLE
4.7 Release

### ISSUE THREAD

**Issue by JohnFF** [veda-consulting/org.civicrm.sms.clickatell#12]
Updating the info file to contain 4.7 in a ver tag doesn't add a release - you need to make a new release for it to be automatically available for download.

**Comment by veda-consulting** [comment]
@JohnFF yep, we're aware, we hadn't got round to running a full test cycle on it, we will do now

**Comment by JohnFF** [comment]
So it's been unavailable on latest for 8 months?

**Comment by veda-consulting** [comment]
@JohnFF yes, we're testing it on the latest versions as we speak.
