### ISSUE TITLE
Has Clickatell changed their authentication API?

### ISSUE THREAD

**Issue by elcapo** [veda-consulting/org.civicrm.sms.clickatell#13]
I'm trying to set up a new environment with a Clickatell integration and I've found that Clickatell is no longer using the **api_id + user + password** combination they where using before. They are now using an apiKey instead (https://twitter.com/Clickatell/status/854656741098782720). Does the extension need to be updated in order to work with this new API? Or maybe I'm missing something?

**Comment by JohnFF** [comment]
Clickatell has entirely changed their API - this extension no longer functions.

**Comment by veda-consulting** [comment]
@JohnFF @elcapo we'll fix this version with the new APIs

**Comment by veda-consulting** [comment]
@elcapo @JohnFF this version works with the new keys
If you put api_key= into the additional params then everything is fine?

**Comment by JohnFF** [comment]
Clickatell maintains two versions of the API. The old way still works through https, however this extension has moved exclusively to the new way. This requires all clients using the old method to update their Clickatell settings - but your extension doesn't tell them that. It just stops working.

**Comment by veda-consulting** [comment]
@JohnFF ok - maybe we can check the settings as part of the move i.e. we could fire a test from the settings page or something and include some instructions?

**Comment by JohnFF** [comment]
To be honest, I have a lot of ideas on how to improve this extension quite considerably. I've dropped you an email. Let's chat :)

**Comment by jorich-2000** [comment]
I am not impressed with the lack of care being taken over maintaining compatibility .  Clickatell have not retired the old api and there are many of us using this still.  Just replacing code would be fine if it didn’t completely remove and break installations that are working.  I have two clients who have had no sms for 6 months now!

**Comment by JohnFF** [comment]
Typically extension maintainers research these things and make sure that their extensions provide the needed features... it's currently 100% broken on all Civi46 installs, and on some Civi47 installs, depending on the API version (with the majority on the old version).

**Comment by JohnFF** [comment]
@jorich-2000 if you want me to deliver something that works email me at john@civifirst.com

**Comment by deepak-srivastava** [comment]
Update: please checkout latest release v4.1 with backward compatibility.

**Comment by veda-consulting** [comment]
Thanks for your patience on this guys

I think its important to note this extension is maintained 100% voluntarily and assuming that we should be checking for the very strange practices that third parties take would be valid if we were financially invested in the relationships. As its voluntary and has zero test coverage we are stuck in the position where we have to find time to resolve issues, some of which could be very tricky.

@JohnFF it would be great if your offer to "deliver something that worked" was made as a PR back to the main extension, after all this is what community extensions are all about!

@jorich-2000 thanks for your debugging efforts on the other issue, we had been doing the same in parallel and came to the same conclusion. We've managed to keep it as a single extension as there is just the one change which is required to keep both sets of API keys working.
