### ISSUE TITLE
The API Link in the interface is overridden in the code.

### ISSUE THREAD

**Issue by JohnFF** [veda-consulting/org.civicrm.sms.clickatell#14]
The API Link in the interface is overridden in the code, which is misleading for users.

**Comment by veda-consulting** [comment]
@JohnFF could you give us an example of what you mean?

**Comment by JohnFF** [comment]
Sure, look in the code: _apiURL is defined with a URL. But then it's never used! #Confusing. It does look like the link in the interface is used after all.

**Comment by veda-consulting** [comment]
@jyothi-shree21 can we remove the bit of code that John is referring to - the definition should still be there but the URL shouldn't be set. Please make sure there aren't any warning etc when you test the code in PHP etc.
