### ISSUE TITLE
No Sender ID on Mass SMS

### ISSUE THREAD

**Issue by hamboneZA** [veda-consulting/org.civicrm.sms.clickatell#16]
Hi!

It would appear that when I send a single SMS via a 'outbound SMS' on a single contact the from:123456789 parameter set is delivered correctly. However, when one sends through Mass SMS no sender ID is set and the generic provider sender is used. 

Any tips?

**Comment by deepak-srivastava** [comment]
@hamboneZA Do you have from parameter set in API Parameters? If not try setting it.

And even when it's set, a Sender ID (from address) differ from country to country and carrier to carrier. See https://www.clickatell.com/faqs/answer/what-is-sender-id.

Also you need to make sure from address is registered with clickatell. If we go to Manage Account > Manage Sender IDs i see a message which shows the similar message:

> 
![image](https://user-images.githubusercontent.com/3448551/40311239-2be7a134-5d07-11e8-83c5-e48886d1a623.png)

Hope that clarifies.

**Comment by deepak-srivastava** [comment]
Closing the issue. Please re-open if any part of extension causing the problem.
