### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [veda-consulting/org.civicrm.sms.clickatell#2]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by francescbassas** [comment]
Any news on this? Is the extension compatible with version 4.6?

**Comment by veda-consulting** [comment]
@francescbassas @magnolia61 we've tested and it seems to working for 4.6, we've updated the information to indicate this.
