### ISSUE TITLE
Mass SMS menu items only appear if administrator

### ISSUE THREAD

**Issue by clarkac1** [veda-consulting/org.civicrm.sms.clickatell#9]
The 2 mass SMS menu items (Mass SMS) and 'Find Mass SMS' are only available for users with 'administer CiviCRM' access. Hence we cannot give this access to regular users.

**Comment by veda-consulting** [comment]
@clarkac1 we'll take a look at the latest permissions structures to see where the extension better sites in terms of roles/permissions

**Comment by veda-consulting** [comment]
@jyothi-shree21 can we add two new permissions for the sending of SMS or if there existing permissions can we use them.

**Comment by deepak-srivastava** [comment]
Core has already introduced the new permission and removed administrator requirement - https://github.com/civicrm/civicrm-core/pull/11590/files#diff-0afaab637f5b2b03bc4cbf04a34e1c7a
https://issues.civicrm.org/jira/browse/CRM-21576

Note: configuring provider would still need administrator access, but not sending.
Closing the issue
